LOCK TABLE clients.companies, clients.individuals IN SHARE ROW EXCLUSIVE MODE;
CREATE TRIGGER wms_client_companies_change AFTER INSERT OR UPDATE OR DELETE ON clients.companies FOR EACH ROW EXECUTE FUNCTION wms.capture_entity_change('App\Models\ClientCompany', '["name", "shortname", "fullname", "inn", "kpp", "ogrn", "okpo", "phone", "email", "site", "director_fio", "director_position", "bank", "bik", "korr_schet", "rasch_schet", "client_id", "src", "status", "tenant_id", "created_at", "updated_at", "deleted_at"]', '{"src": ["telegram", "opf", "accountant_position", "accountant_fio", "legal_address", "is_own", "is_client", "is_partner"]}');
CREATE TRIGGER wms_client_companies_truncate BEFORE TRUNCATE ON clients.companies FOR EACH STATEMENT EXECUTE FUNCTION wms.capture_entity_truncate('App\Models\ClientCompany');
CREATE TRIGGER wms_client_individuals_change AFTER INSERT OR UPDATE OR DELETE ON clients.individuals FOR EACH ROW EXECUTE FUNCTION wms.capture_entity_change('App\Models\ClientIndividual', '["name", "shortname", "firstname", "middlename", "lastname", "phone", "email", "birthday", "passport_seria", "passport_number", "passport_date", "passport_kem", "passport_code", "address_reg", "vodud_date", "vodud_nomer", "user_id", "manager_id", "client_id", "status", "tenant_id", "created_at", "updated_at", "deleted_at"]');
CREATE TRIGGER wms_client_individuals_truncate BEFORE TRUNCATE ON clients.individuals FOR EACH STATEMENT EXECUTE FUNCTION wms.capture_entity_truncate('App\Models\ClientIndividual');
DO $$
DECLARE item record;
BEGIN
FOR item IN SELECT * FROM (SELECT 'App\Models\ClientCompany' AS entity, id::text AS id, tenant_id, jsonb_build_object('id', id::text, 'name', name, 'shortname', shortname, 'fullname', fullname, 'inn', inn, 'kpp', kpp, 'ogrn', ogrn, 'okpo', okpo, 'phone', phone, 'email', email, 'site', site, 'director_fio', director_fio, 'director_position', director_position, 'bank', bank, 'bik', bik, 'korr_schet', korr_schet, 'rasch_schet', rasch_schet, 'client_id', client_id, 'src', jsonb_build_object('telegram', src::jsonb->'telegram', 'opf', src::jsonb->'opf', 'accountant_position', src::jsonb->'accountant_position', 'accountant_fio', src::jsonb->'accountant_fio', 'legal_address', src::jsonb->'legal_address', 'is_own', src::jsonb->'is_own', 'is_client', src::jsonb->'is_client', 'is_partner', src::jsonb->'is_partner'), 'status', status, 'tenant_id', tenant_id, 'created_at', created_at, 'updated_at', updated_at, 'deleted_at', deleted_at) AS data FROM clients.companies UNION ALL SELECT 'App\Models\ClientIndividual' AS entity, id::text AS id, tenant_id, jsonb_build_object('id', id::text, 'name', name, 'shortname', shortname, 'firstname', firstname, 'middlename', middlename, 'lastname', lastname, 'phone', phone, 'email', email, 'birthday', birthday, 'passport_seria', passport_seria, 'passport_number', passport_number, 'passport_date', passport_date, 'passport_kem', passport_kem, 'passport_code', passport_code, 'address_reg', address_reg, 'vodud_date', vodud_date, 'vodud_nomer', vodud_nomer, 'user_id', user_id, 'manager_id', manager_id, 'client_id', client_id, 'status', status, 'tenant_id', tenant_id, 'created_at', created_at, 'updated_at', updated_at, 'deleted_at', deleted_at) AS data FROM clients.individuals) rows ORDER BY tenant_id COLLATE "C" NULLS FIRST, entity, id COLLATE "C" LOOP
PERFORM wms.append_entity_change(item.entity, item.tenant_id, item.id, 'upsert', item.data);
END LOOP;
END;
$$;
