LOCK TABLE integration.webhooks, integration.data, integration.rules, integration.services, integration.type_hook, integration.type_processing IN SHARE ROW EXCLUSIVE MODE;
CREATE TRIGGER wms_integration_webhooks_change AFTER INSERT OR UPDATE OR DELETE ON integration.webhooks FOR EACH ROW EXECUTE FUNCTION wms.capture_entity_change('App\Models\IntegrationWebhook', '["id", "name", "shortname", "status", "tenant_id", "created_at", "updated_at", "deleted_at", "service_id", "type_hook_id", "rules_id", "cnt", "dat_last_run"]');
CREATE TRIGGER wms_integration_webhooks_truncate BEFORE TRUNCATE ON integration.webhooks FOR EACH STATEMENT EXECUTE FUNCTION wms.capture_entity_truncate('App\Models\IntegrationWebhook');
CREATE TRIGGER wms_integration_data_change AFTER INSERT OR UPDATE OR DELETE ON integration.data FOR EACH ROW EXECUTE FUNCTION wms.capture_entity_change('App\Models\IntegrationData', '["id", "name", "shortname", "status", "tenant_id", "created_at", "updated_at", "deleted_at", "webhook_id", "service_id", "status_processing"]');
CREATE TRIGGER wms_integration_data_truncate BEFORE TRUNCATE ON integration.data FOR EACH STATEMENT EXECUTE FUNCTION wms.capture_entity_truncate('App\Models\IntegrationData');
CREATE TRIGGER wms_integration_rules_change AFTER INSERT OR UPDATE OR DELETE ON integration.rules FOR EACH ROW EXECUTE FUNCTION wms.capture_entity_change('App\Models\IntegrationRule', '["id", "name", "shortname", "status", "tenant_id", "created_at", "updated_at", "deleted_at", "type_processing_id"]');
CREATE TRIGGER wms_integration_rules_truncate BEFORE TRUNCATE ON integration.rules FOR EACH STATEMENT EXECUTE FUNCTION wms.capture_entity_truncate('App\Models\IntegrationRule');
CREATE TRIGGER wms_integration_services_change AFTER INSERT OR UPDATE OR DELETE ON integration.services FOR EACH ROW EXECUTE FUNCTION wms.capture_entity_change('App\Models\IntegrationService', '["id", "name", "shortname", "status", "tenant_id", "created_at", "updated_at", "deleted_at"]');
CREATE TRIGGER wms_integration_services_truncate BEFORE TRUNCATE ON integration.services FOR EACH STATEMENT EXECUTE FUNCTION wms.capture_entity_truncate('App\Models\IntegrationService');
CREATE TRIGGER wms_integration_type_hook_change AFTER INSERT OR UPDATE OR DELETE ON integration.type_hook FOR EACH ROW EXECUTE FUNCTION wms.capture_entity_change('App\Models\IntegrationHookType', '["id", "name", "shortname", "status", "tenant_id", "created_at", "updated_at", "deleted_at"]');
CREATE TRIGGER wms_integration_type_hook_truncate BEFORE TRUNCATE ON integration.type_hook FOR EACH STATEMENT EXECUTE FUNCTION wms.capture_entity_truncate('App\Models\IntegrationHookType');
CREATE TRIGGER wms_integration_type_processing_change AFTER INSERT OR UPDATE OR DELETE ON integration.type_processing FOR EACH ROW EXECUTE FUNCTION wms.capture_entity_change('App\Models\IntegrationProcessingType', '["id", "name", "shortname", "status", "tenant_id", "created_at", "updated_at", "deleted_at"]');
CREATE TRIGGER wms_integration_type_processing_truncate BEFORE TRUNCATE ON integration.type_processing FOR EACH STATEMENT EXECUTE FUNCTION wms.capture_entity_truncate('App\Models\IntegrationProcessingType');
DO $$ DECLARE item record; BEGIN
FOR item IN SELECT * FROM (SELECT 'App\Models\IntegrationWebhook' AS entity, id::text AS id, tenant_id, jsonb_build_object('id', id::text, 'name', name, 'shortname', shortname, 'status', status, 'tenant_id', tenant_id, 'created_at', created_at, 'updated_at', updated_at, 'deleted_at', deleted_at, 'service_id', service_id, 'type_hook_id', type_hook_id, 'rules_id', rules_id, 'cnt', cnt, 'dat_last_run', dat_last_run) AS data FROM integration.webhooks UNION ALL SELECT 'App\Models\IntegrationData' AS entity, id::text AS id, tenant_id, jsonb_build_object('id', id::text, 'name', name, 'shortname', shortname, 'status', status, 'tenant_id', tenant_id, 'created_at', created_at, 'updated_at', updated_at, 'deleted_at', deleted_at, 'webhook_id', webhook_id, 'service_id', service_id, 'status_processing', status_processing) AS data FROM integration.data UNION ALL SELECT 'App\Models\IntegrationRule' AS entity, id::text AS id, tenant_id, jsonb_build_object('id', id::text, 'name', name, 'shortname', shortname, 'status', status, 'tenant_id', tenant_id, 'created_at', created_at, 'updated_at', updated_at, 'deleted_at', deleted_at, 'type_processing_id', type_processing_id) AS data FROM integration.rules UNION ALL SELECT 'App\Models\IntegrationService' AS entity, id::text AS id, tenant_id, jsonb_build_object('id', id::text, 'name', name, 'shortname', shortname, 'status', status, 'tenant_id', tenant_id, 'created_at', created_at, 'updated_at', updated_at, 'deleted_at', deleted_at) AS data FROM integration.services UNION ALL SELECT 'App\Models\IntegrationHookType' AS entity, id::text AS id, tenant_id, jsonb_build_object('id', id::text, 'name', name, 'shortname', shortname, 'status', status, 'tenant_id', tenant_id, 'created_at', created_at, 'updated_at', updated_at, 'deleted_at', deleted_at) AS data FROM integration.type_hook UNION ALL SELECT 'App\Models\IntegrationProcessingType' AS entity, id::text AS id, tenant_id, jsonb_build_object('id', id::text, 'name', name, 'shortname', shortname, 'status', status, 'tenant_id', tenant_id, 'created_at', created_at, 'updated_at', updated_at, 'deleted_at', deleted_at) AS data FROM integration.type_processing) rows ORDER BY tenant_id COLLATE "C" NULLS FIRST, entity, id COLLATE "C" LOOP
PERFORM wms.append_entity_change(item.entity, item.tenant_id, item.id, 'upsert', item.data);
END LOOP; END; $$;
