LOCK TABLE wms.sync_state IN ACCESS EXCLUSIVE MODE;
LOCK TABLE public.entity_changes IN ACCESS EXCLUSIVE MODE;
CREATE TABLE public.sync_state (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id varchar(255),
    revision bigint NOT NULL DEFAULT 0,
    generation varchar(32) NOT NULL DEFAULT md5(random()::text || clock_timestamp()::text),
    CONSTRAINT sync_state_tenant_unique UNIQUE NULLS NOT DISTINCT (tenant_id)
);
INSERT INTO public.sync_state (tenant_id, revision)
SELECT tenant_id, max(revision) FROM public.entity_changes GROUP BY tenant_id;
ALTER TABLE public.entity_changes DROP CONSTRAINT user_changes_pkey;
ALTER TABLE public.entity_changes ADD CONSTRAINT entity_changes_tenant_revision_unique UNIQUE NULLS NOT DISTINCT (tenant_id, revision);
DROP TABLE wms.sync_state;
