name: api
model: Send_message
titleMenu: Send_message
descr:
    one: 'отправленное сообщение'
table: send_messages
module: messenger
fields:
    account_id:
        type: integer
        comment: account_id
        nullable: true
        example: ''
    channel_id:
        type: integer
        comment: channel_id
        nullable: true
        example: ''
    message:
        type: text
        comment: Сообщение
        nullable: true
        example: ''
    files:
        type: json
        comment: Файл
        nullable: true
        example: ''
    response:
        type: json
        comment: 'Ответ после отправки'
        nullable: true
        example: ''
    status:
        type: integer
        comment: '0 - new, 1 - sent, 2 - blocked, 3 - in progress'
        nullable: true
        example: ''
