name: api
model: ServiceAccount
descr:
  about: 'о ком чем?'
  many_r: 'много кого чего?'
  one: сервисный аккаунт
table: service_accounts
module: Messenger
fields:
  name:
    type: string
    comment: Название
    nullable: true
    example: ''
  shortname:
    type: string
    comment: 'Короткое название'
    nullable: true
    example: ''
  service_id:
    type: integer
    comment: 'Сервис'
    nullable: true
    example: ''
  login:
    type: string
    comment: 'Логин'
    nullable: true
    example: ''
  password:
    type: string
    comment: 'Пароль'
    nullable: true
    example: ''
  token:
    type: string
    comment: 'Токен'
    nullable: true
    example: ''
  options:
    type: json
    comment: Параметры
    nullable: true
    example: ''
  status:
    type: integer
    comment: Статус
    nullable: true
    example: ''
  balance:
    type: double
    comment: Баланс
    nullable: true
    example: ''
  cnt:
    type: integer
    comment: Количество
    nullable: true
    example: ''
menu:
  name: Сервисные аккаунты
  shortname: messenger.serviccaccount
  is_api: 2
  level: 3
  page: /web/messenger/serviceaccount
  api: 'https://messenger.itstaffer.ru/api/serviceaccount'
  model: Modules\Messenger\Models\ServiceAccount
  settings:
    fields:
      name:
        name: Название
        field_mode: 'index,create,edit,show'
        control: text
        db_type: string
        is_lookup: false
      shortname:
        name: 'Короткое название'
        field_mode: 'index,create,edit,show'
        control: text
        db_type: string
        is_lookup: false
      balance:
        name: Баланс
        field_mode: 'create,edit,show'
        control: json
        db_type: string
        is_lookup: false
      status:
        name: Статус
        field_mode: 'index,create,edit,show'
        control: status
        db_type: integer
        is_lookup: false
  icon: 'uil uil-user'
  status: 1
  is_list: 1
  parent_shortname: chats.lists
