<script setup lang="ts">
import { onMounted, ref } from "vue"; import { Head } from "@inertiajs/vue3"; import MaintenanceTabs from "../Components/MaintenanceTabs.vue"; import { http, HttpError } from "../lib/http";
interface Task { id:number; name:string; shortname:string; task_type:string; target:string; options:Record<string, unknown>; status:number }
const rows=ref<Task[]>([]); const editing=ref<Task|null>(null); const open=ref(false); const error=ref(""); const form=ref({name:"",shortname:"",task_type:"command",target:"",options:'{"required":{},"optional":{}}',status:1});
function reset(row?:Task){editing.value=row??null;open.value=true;form.value=row?{name:row.name,shortname:row.shortname,task_type:row.task_type,target:row.target,options:JSON.stringify(row.options??{},null,2),status:row.status}:{name:"",shortname:"",task_type:"command",target:"",options:'{"required":{},"optional":{}}',status:1};}
async function load(){try{rows.value=(await http('/web/scheduler-tasks')).data??[]}catch(e){error.value=e instanceof HttpError?e.message:'Не удалось загрузить задачи.';}}
async function save(){try{error.value="";const options=JSON.parse(form.value.options||'{}');await http(editing.value?`/web/scheduler-tasks/${editing.value.id}`:'/web/scheduler-tasks',editing.value?'PUT':'POST',{...form.value,options});open.value=false;await load();}catch(e){error.value=e instanceof HttpError?e.message:(e as Error).message;}}
async function remove(row:Task){if(confirm(`Удалить задачу «${row.name}»?`)){await http(`/web/scheduler-tasks/${row.id}`,'DELETE');await load();}}
onMounted(load);
</script>
<template><Head title="Задачи планировщика" /><div class="scheduler-workspace"><section class="scheduler-main"><div class="content-breadcrumb">Обслуживание › Справочники › Задачи</div><MaintenanceTabs/><div class="page-heading"><div><h1>Задачи</h1><p class="muted">Задачи, доступные для планирования в модуле WMS</p></div><button class="primary" type="button" @click="reset()">Добавить задачу</button></div><p v-if="error" class="notice error">{{error}}</p><div class="table-scroll"><table><thead><tr><th>#</th><th>Название</th><th>Код</th><th>Тип</th><th>Обработчик</th><th>Параметры</th><th>Действия</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td>{{row.id}}</td><td>{{row.name}}</td><td>{{row.shortname}}</td><td>{{row.task_type}}</td><td>{{row.target}}</td><td>{{Object.keys((row.options as any)?.required??{}).length}} обязательных / {{Object.keys((row.options as any)?.optional??{}).length}} необязательных</td><td><div class="row-actions"><button type="button" aria-label="Редактировать" title="Редактировать" @click="reset(row)"><img src="/design/crm/edit.svg" alt=""></button><button type="button" aria-label="Удалить" title="Удалить" @click="remove(row)"><img src="/design/crm/delete.svg" alt=""></button></div></td></tr></tbody></table></div></section><aside v-if="open" class="editor"><header><div><small>{{editing?'РЕДАКТИРОВАНИЕ':'НОВАЯ ЗАДАЧА'}}</small><h2>{{editing?'Задача':'Новая задача'}}</h2></div><button @click="open=false">×</button></header><div class="editor-content"><form @submit.prevent="save"><label>Название<input v-model="form.name" required></label><label>Код<input v-model="form.shortname" required></label><label>Тип<select v-model="form.task_type"><option value="command">Команда Artisan</option><option value="job">Job-класс</option></select></label><label>Обработчик<input v-model="form.target" required></label><label>Параметры JSON<textarea v-model="form.options" rows="12"></textarea></label><button class="primary">Сохранить</button></form></div></aside></div></template>
<style scoped>.scheduler-workspace{display:flex;min-height:0;flex:1;overflow:hidden;background:#fff;border:1px solid var(--crm-border);border-radius:10px}.scheduler-main{display:flex;flex:1;min-width:0;flex-direction:column;overflow:auto;padding:30px}.scheduler-main table{width:100%;border-collapse:collapse}.scheduler-main th,.scheduler-main td{padding:12px 10px;text-align:left;border-bottom:1px solid #edf0f3}.scheduler-main .page-heading{padding:26px 0 21px}.link-button{border:0;background:transparent;color:#1e892f;cursor:pointer;margin-right:10px}.danger{color:#a32626}.editor{width:390px;flex-shrink:0}@media(max-width:900px){.scheduler-workspace{display:block;overflow:auto}.scheduler-main{padding:18px 12px}.editor{width:auto;border-top:1px solid #e8ecf0}}</style>
