<script setup lang="ts">
import { computed, onMounted, ref, watch } from "vue";
import { http } from "../lib/http";
import RussianDateInput from "../Components/RussianDateInput.vue";
import AdminTabs from "../Components/AdminTabs.vue";
import { isoDate, toIsoDate } from "../lib/dates";
const today = new Date(), from = ref(toIsoDate(new Date(today.getFullYear(), today.getMonth(), 1))), to = ref(toIsoDate(new Date(today.getFullYear(), today.getMonth() + 1, 0))), report = ref<any>({ days: [], rows: [] }), loading = ref(false), error = ref("");
const weekdays = ["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"];
const info = (row: any, day: string) => row.days?.[day] || { state: "empty", worked_minutes: 0 };
const hours = (minutes: number) => minutes ? `${Math.floor(minutes / 60)}ч` : "";
const label = (day: string) => { const d = isoDate(day)!; return `${String(d.getDate()).padStart(2, "0")} ${weekdays[d.getDay()]}`; };
const isWeekend = (day: string) => { const index = isoDate(day)!.getDay(); return index === 0 || index === 6; };
const monthGroups = computed(() => { const groups: { key: string; label: string; count: number }[] = []; for (const day of report.value.days) { const date = isoDate(day)!; const key = `${date.getFullYear()}-${date.getMonth()}`; const current = groups.at(-1); if (current?.key === key) current.count += 1; else groups.push({ key, label: date.toLocaleDateString("ru-RU", { month: "long", year: "numeric" }), count: 1 }); } return groups; });
const total = (row: any) => Object.values(row.days || {}).reduce((sum: number, d: any) => sum + (d.worked_minutes || 0), 0);
async function load() { if (!from.value || !to.value) return; loading.value = true; try { report.value = await http(`/web/worktime?from=${from.value}&to=${to.value}`); } catch (e: any) { error.value = e?.message || "Не удалось загрузить график."; } finally { loading.value = false; } }
onMounted(load); watch([from, to], load);
</script>
<template><div class="worktime-page"><AdminTabs /><section class="card"><div class="heading"><div><h1>График присутствий и отсутствий</h1><p>Рабочее время сотрудников</p></div><div class="range"><RussianDateInput v-model="from" /><span>—</span><RussianDateInput v-model="to" /></div></div><p v-if="error" class="error">{{ error }}</p><div class="calendar" :class="{ busy: loading }"><table><thead><tr class="month-row"><th class="employee" rowspan="2">Сотрудник</th><th v-for="group in monthGroups" :key="group.key" :colspan="group.count">{{ group.label }}</th><th class="total" rowspan="2">Итого</th></tr><tr class="day-row"><th v-for="day in report.days" :key="day">{{ label(day) }}</th></tr></thead><tbody><tr v-for="row in report.rows" :key="row.user.id"><td class="employee"><strong>{{ [row.user.last_name, row.user.name].filter(Boolean).join(' ') || row.user.email }}</strong></td><td v-for="day in report.days" :key="day" :class="['day', info(row, day).state, { weekend: isWeekend(day) }]">{{ hours(info(row, day).worked_minutes) }}</td><td class="total">{{ hours(total(row)) }}</td></tr><tr v-if="!report.rows.length"><td :colspan="report.days.length + 2" class="empty">Нет данных</td></tr></tbody></table></div><div class="legend"><span><i class="present"></i>Присутствие</span><span><i class="paused"></i>Пауза</span><span><i class="absence"></i>Больничный</span><span><i class="absence"></i>Отпуск</span></div></section></div></template>
<style scoped>
.worktime-page{padding:24px 32px}.card{background:#fff;border:1px solid #dcecef;border-radius:12px;padding:24px;overflow:hidden}.heading{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}h1{margin:0;color:#0c1821;font-size:24px}.heading p{color:#71828a;margin:6px 0 0}.range{display:flex;align-items:center;gap:8px}.range :deep(input){width:115px;padding:9px 10px;border:1px solid #bcdfe7;border-radius:7px}.calendar{overflow:auto}.busy{opacity:.55}table{border-collapse:collapse;min-width:100%;font-size:12px}th,td{border-bottom:1px solid #edf3f4;padding:10px 8px;text-align:center;white-space:nowrap}th{color:#71828a}.month-row th{height:30px;background:#f5f8f9;color:#536168;font-weight:700;text-transform:capitalize}.day-row th{height:42px;background:#fff;color:#71828a}.employee{text-align:left;min-width:180px;position:sticky;left:0;background:#fff;z-index:1}.employee small{display:block;color:#71828a;margin-top:3px}.day{min-width:62px;height:42px}.day.working{background:#c5e5ef;color:#176889}.day.finished{background:#9ed3e2;color:#0f5d79;font-weight:700}.day.paused{background:#ffdd83;color:#765300;font-weight:600}.day.empty{background:#f4f6f6;color:#b7c0c4}.day.weekend{background:#e5e9ea;color:#8d999e}.total{font-weight:700;min-width:80px}.empty{padding:32px;color:#71828a}.legend{display:flex;gap:20px;margin-top:20px;color:#71828a;font-size:12px}.legend span{display:flex;align-items:center;gap:6px}.legend i{width:10px;height:10px;border-radius:3px;display:inline-block}.present{background:#e1f0f3}.paused{background:#fff5dc}.absence{background:#f2f2f2}.error{color:#c43e3e}
</style>
