<script setup lang="ts">
import { onMounted, ref, watch } from "vue";
import RussianDateInput from "./RussianDateInput.vue";
type Schedule = { kind: "interval" | "weekly" | "monthly"; interval: number; unit: "minute" | "hour" | "day"; week_interval: number; weekdays: number[]; month_days: number[]; start_date: string; end_date: string; time: string };
const props = defineProps<{ modelValue?: string | Record<string, any> | null; disabled?: boolean }>();
const emit = defineEmits<{ "update:modelValue": [value: string] }>();
const weekdays = [[1, "Пн"], [2, "Вт"], [3, "Ср"], [4, "Чт"], [5, "Пт"], [6, "Сб"], [7, "Вс"]] as [number, string][];
function moscowDate(): string { const parts = new Intl.DateTimeFormat("en-GB", { timeZone: "Europe/Moscow", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date()); const values = Object.fromEntries(parts.map((part) => [part.type, part.value])); return `${values.year}-${values.month}-${values.day}`; }
function fallback(): Schedule { return { kind: "interval", interval: 1, unit: "hour", week_interval: 1, weekdays: [1], month_days: [1], start_date: moscowDate(), end_date: "", time: "09:00" }; }
function parse(value: unknown): Schedule { try { const parsed = typeof value === "string" ? JSON.parse(value) : value; return { ...fallback(), ...(parsed ?? {}) }; } catch { return fallback(); } }
const schedule = ref<Schedule>(parse(props.modelValue));
const preset = ref("hour_1");
function presetFor(value: Schedule): string { if (value.kind === "weekly") return value.week_interval === 2 ? "biweekly" : value.weekdays.join(",") === "1,2,3,4,5" ? "weekdays" : "weekly"; if (value.kind === "monthly") return "monthly"; if (value.unit === "day") return "daily"; return `${value.unit}_${value.interval}`; }
preset.value = presetFor(schedule.value);
function apply(value: string) { preset.value = value; if (["weekly", "biweekly", "weekdays"].includes(value)) { schedule.value.kind = "weekly"; schedule.value.week_interval = value === "biweekly" ? 2 : 1; schedule.value.weekdays = value === "weekdays" ? [1, 2, 3, 4, 5] : [1]; } else if (value === "monthly") schedule.value.kind = "monthly"; else { schedule.value.kind = "interval"; const [unit, amount] = value === "daily" ? ["day", "1"] : value.split("_"); schedule.value.unit = unit as Schedule["unit"]; schedule.value.interval = Number(amount) || 1; } emitValue(); }
function toggle(day: number) { const index = schedule.value.weekdays.indexOf(day); index >= 0 ? schedule.value.weekdays.splice(index, 1) : schedule.value.weekdays.push(day); emitValue(); }
function emitValue() { emit("update:modelValue", JSON.stringify(schedule.value)); }
watch(() => props.modelValue, (value) => { schedule.value = parse(value); preset.value = presetFor(schedule.value); });
watch(schedule, emitValue, { deep: true });
onMounted(emitValue);
</script>
<template><div class="scheduler-repeat-editor"><div class="repeat-line"><span>Повторять</span><select v-model="preset" :disabled="disabled" @change="apply(preset)"><option value="hour_1">Каждый час</option><option value="hour_2">Каждые 2 часа</option><option value="hour_4">Каждые 4 часа</option><option value="hour_6">Каждые 6 часов</option><option value="hour_8">Каждые 8 часов</option><option value="hour_12">Каждые 12 часов</option><option value="minute_1">Каждую минуту</option><option value="minute_5">Каждые 5 минут</option><option value="minute_10">Каждые 10 минут</option><option value="minute_15">Каждые 15 минут</option><option value="minute_30">Каждые 30 минут</option><option value="daily">Каждый день</option><option value="weekdays">По будням</option><option value="weekly">Каждую неделю</option><option value="biweekly">Каждые 2 недели</option><option value="monthly">Каждый месяц</option></select></div><div class="repeat-dates"><label>Начало<RussianDateInput v-model="schedule.start_date" /></label><label>Время<input v-model="schedule.time" type="time" :disabled="disabled"></label><label>До (необязательно)<RussianDateInput v-model="schedule.end_date" /></label></div><div v-if="schedule.kind === 'weekly'" class="repeat-week"><span>Дни недели</span><label v-for="day in weekdays" :key="day[0]"><input type="checkbox" :checked="schedule.weekdays.includes(day[0])" :disabled="disabled" @change="toggle(day[0])">{{ day[1] }}</label></div><label v-if="schedule.kind === 'monthly'" class="repeat-month">Дни месяца (через запятую)<input :value="schedule.month_days.join(', ')" :disabled="disabled" @input="schedule.month_days = ($event.target as HTMLInputElement).value.split(',').map(Number).filter(Boolean)"></label></div></template>
<style scoped>.scheduler-repeat-editor{display:grid;gap:12px;padding:12px;border:1px solid #dcecef;border-radius:8px;background:#f8fbfb}.repeat-line{display:grid;grid-template-columns:92px 1fr;align-items:center;gap:10px}.repeat-dates{display:grid;grid-template-columns:1fr 1fr;gap:10px}.repeat-dates label,.repeat-month{display:grid;gap:5px;color:#52636a;font-size:12px}.repeat-week{display:flex;flex-wrap:wrap;gap:8px 12px;padding-top:10px;border-top:1px solid #e3ecee;color:#52636a;font-size:12px}.repeat-week span{width:100%;font-weight:600}.repeat-week label{display:flex;align-items:center;gap:4px}</style>
