<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /** @var array<string, string> */
    private array $sources = [
        'access.services' => 'App\\Models\\AccessService',
        'clients.services' => 'App\\Models\\ClientService',
        'integration.services' => 'App\\Models\\IntegrationService',
        'dating.services' => 'App\\Models\\DatingService',
        'messenger.services' => 'App\\Models\\MessengerService',
        'support.services' => 'App\\Models\\SupportService',
        'fakes.service' => 'App\\Models\\FakeService',
        'pay.service' => 'App\\Models\\PayService',
        'video.service' => 'App\\Models\\VideoService',
    ];

    public function up(): void
    {
        DB::statement("SET LOCAL lock_timeout = '5s'");
        DB::statement("SET LOCAL statement_timeout = '120s'");

        DB::statement('CREATE SCHEMA IF NOT EXISTS shared');
        DB::unprepared(<<<'SQL'
CREATE TABLE shared.services (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_schema varchar(63) NOT NULL,
    source_table varchar(63) NOT NULL,
    source_id bigint NOT NULL,
    name varchar(255),
    shortname varchar(255),
    status integer,
    category_id bigint,
    options jsonb,
    cnt integer,
    tags jsonb,
    tenant_id varchar(255),
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    CONSTRAINT shared_services_source_key UNIQUE (source_schema, source_table, source_id)
);
CREATE INDEX shared_services_tenant_id_index ON shared.services (tenant_id);
CREATE INDEX shared_services_shortname_index ON shared.services (shortname);
CREATE INDEX shared_services_status_index ON shared.services (status);
SQL);

        foreach ($this->sources as $qualified => $entity) {
            [$schema, $table] = explode('.', $qualified, 2);
            $columns = DB::select(
                'SELECT column_name FROM information_schema.columns WHERE table_schema = ? AND table_name = ? ORDER BY ordinal_position',
                [$schema, $table],
            );
            if ($columns === []) {
                continue;
            }

            $available = array_fill_keys(array_map(static fn (object $column): string => $column->column_name, $columns), true);
            $value = static function (string $column) use ($available): string {
                return isset($available[$column]) ? 's.'.($column === 'options' || $column === 'tags' ? $column.'::jsonb' : $column) : 'NULL';
            };

            DB::statement(
                "INSERT INTO shared.services (source_schema, source_table, source_id, name, shortname, status, category_id, options, cnt, tags, tenant_id, created_at, updated_at, deleted_at)\n"
                ."SELECT ?, ?, s.id, {$value('name')}, {$value('shortname')}, {$value('status')}, {$value('category_id')}, {$value('options')}, {$value('cnt')}, {$value('tags')}, {$value('tenant_id')}, {$value('created_at')}, {$value('updated_at')}, {$value('deleted_at')}\n"
                ."FROM {$schema}.{$table} s",
                [$schema, $table],
            );
        }

        $this->dropForeignKeysToSources();
        $this->rewriteServiceReferences();

        foreach ($this->sources as $qualified => $entity) {
            [$schema, $table] = explode('.', $qualified, 2);
            DB::statement("DROP TRIGGER IF EXISTS wms_{$schema}_{$table}_change ON {$schema}.{$table}");
            DB::statement("DROP TRIGGER IF EXISTS wms_{$schema}_{$table}_truncate ON {$schema}.{$table}");
            DB::statement("ALTER TABLE {$schema}.{$table} RENAME TO __{$table}");
        }

        DB::unprepared(<<<'SQL'
CREATE OR REPLACE FUNCTION shared.service_changed() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog AS $$
DECLARE
    payload jsonb;
    kind text;
    item_id text;
    item_tenant text;
    row_data jsonb;
BEGIN
    IF TG_OP = 'INSERT' THEN
        kind := CASE NEW.source_schema || '.' || NEW.source_table
            WHEN 'clients.services' THEN 'App\Models\ClientService'
            WHEN 'integration.services' THEN 'App\Models\IntegrationService'
            ELSE 'App\Models\SharedService'
        END;
    ELSE
        kind := CASE OLD.source_schema || '.' || OLD.source_table
            WHEN 'clients.services' THEN 'App\Models\ClientService'
            WHEN 'integration.services' THEN 'App\Models\IntegrationService'
            ELSE 'App\Models\SharedService'
        END;
        row_data := to_jsonb(OLD);
        item_id := OLD.id::text;
        item_tenant := OLD.tenant_id;
    END IF;
    IF TG_OP = 'DELETE' THEN
        PERFORM wms.append_entity_change(kind, item_tenant, item_id, 'remove');
        RETURN OLD;
    END IF;
    row_data := to_jsonb(NEW) - 'source_schema' - 'source_table' - 'source_id';
    item_id := NEW.id::text;
    item_tenant := NEW.tenant_id;
    PERFORM wms.append_entity_change(kind, item_tenant, item_id, 'upsert', row_data);
    RETURN NEW;
END;
$$;

CREATE TRIGGER shared_services_changed
AFTER INSERT OR UPDATE OR DELETE ON shared.services
FOR EACH ROW EXECUTE FUNCTION shared.service_changed();

CREATE OR REPLACE FUNCTION shared.service_view_write() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog AS $$
DECLARE
    data jsonb;
    item_id bigint;
    v_source_schema text := TG_ARGV[0];
    v_source_table text := TG_ARGV[1];
BEGIN
    IF TG_OP = 'INSERT' THEN
        item_id := nextval('shared.services_id_seq');
        data := to_jsonb(NEW);
        INSERT INTO shared.services (id, source_schema, source_table, source_id, name, shortname, status,
            category_id, options, cnt, tags, tenant_id, created_at, updated_at, deleted_at)
        VALUES (item_id, v_source_schema, v_source_table, item_id,
            data->>'name', data->>'shortname', (data->>'status')::integer,
            (data->>'category_id')::bigint, data->'options', (data->>'cnt')::integer,
            data->'tags', data->>'tenant_id', (data->>'created_at')::timestamp,
            (data->>'updated_at')::timestamp, (data->>'deleted_at')::timestamp);
        NEW.id := item_id;
        RETURN NEW;
    END IF;

    IF TG_OP = 'DELETE' THEN
        UPDATE shared.services SET deleted_at = clock_timestamp(), updated_at = clock_timestamp()
        WHERE id = OLD.id AND source_schema = v_source_schema AND source_table = v_source_table;
        RETURN OLD;
    END IF;

    data := to_jsonb(NEW);
    UPDATE shared.services SET
        name = CASE WHEN data ? 'name' THEN data->>'name' ELSE name END,
        shortname = CASE WHEN data ? 'shortname' THEN data->>'shortname' ELSE shortname END,
        status = CASE WHEN data ? 'status' THEN (data->>'status')::integer ELSE status END,
        category_id = CASE WHEN data ? 'category_id' THEN (data->>'category_id')::bigint ELSE category_id END,
        options = CASE WHEN data ? 'options' THEN data->'options' ELSE options END,
        cnt = CASE WHEN data ? 'cnt' THEN (data->>'cnt')::integer ELSE cnt END,
        tags = CASE WHEN data ? 'tags' THEN data->'tags' ELSE tags END,
        tenant_id = CASE WHEN data ? 'tenant_id' THEN data->>'tenant_id' ELSE tenant_id END,
        created_at = CASE WHEN data ? 'created_at' THEN (data->>'created_at')::timestamp ELSE created_at END,
        updated_at = CASE WHEN data ? 'updated_at' THEN (data->>'updated_at')::timestamp ELSE clock_timestamp() END,
        deleted_at = CASE WHEN data ? 'deleted_at' THEN (data->>'deleted_at')::timestamp ELSE deleted_at END
    WHERE id = NEW.id AND source_schema = v_source_schema AND source_table = v_source_table;
    RETURN NEW;
END;
$$;
SQL);

        DB::table('public.entity_changes')
            ->whereIn('entity', array_values($this->sources))
            ->delete();
        DB::statement('UPDATE public.sync_state SET generation = md5(random()::text || clock_timestamp()::text)');

        foreach ($this->sources as $qualified => $entity) {
            [$schema, $table] = explode('.', $qualified, 2);
            $backup = "__{$table}";
            $columns = DB::select(
                'SELECT column_name, udt_name FROM information_schema.columns WHERE table_schema = ? AND table_name = ? ORDER BY ordinal_position',
                [$schema, $backup],
            );
            $sharedColumns = ['id', 'name', 'shortname', 'status', 'category_id', 'options', 'cnt', 'tags', 'tenant_id', 'created_at', 'updated_at', 'deleted_at'];
            $viewColumns = array_values(array_filter(
                $columns,
                static fn (object $column): bool => in_array($column->column_name, $sharedColumns, true),
            ));
            $selectColumns = array_map(static function (object $column): string {
                $cast = match ($column->udt_name) {
                    'json' => '::json',
                    'int2' => '::smallint',
                    default => '',
                };

                return '"'.$column->column_name.'"'.$cast;
            }, $viewColumns);
            $quotedColumns = implode(', ', $selectColumns);
            DB::statement("CREATE VIEW {$schema}.{$table} AS SELECT {$quotedColumns} FROM shared.services WHERE source_schema = '{$schema}' AND source_table = '{$table}'");
            DB::statement("CREATE TRIGGER shared_{$table}_view_write INSTEAD OF INSERT OR UPDATE OR DELETE ON {$schema}.{$table} FOR EACH ROW EXECUTE FUNCTION shared.service_view_write('{$schema}', '{$table}')");
        }

        foreach (DB::table('shared.services')->orderBy('id')->get() as $service) {
            $source = $service->source_schema.'.'.$service->source_table;
            $entity = $source === 'clients.services'
                ? 'App\\Models\\ClientService'
                : ($source === 'integration.services' ? 'App\\Models\\IntegrationService' : 'App\\Models\\SharedService');
            $payload = array_filter((array) $service, static fn (mixed $value, string $key): bool => ! in_array($key, ['source_schema', 'source_table', 'source_id'], true), ARRAY_FILTER_USE_BOTH);
            DB::select('SELECT wms.append_entity_change(?, ?, ?, ?, ?::jsonb)', [
                $entity,
                $service->tenant_id,
                (string) $service->id,
                'upsert',
                json_encode($payload, JSON_THROW_ON_ERROR | JSON_UNESCAPED_UNICODE),
            ]);
        }

        DB::statement('ALTER TABLE clients.accounts ADD CONSTRAINT clients_accounts_service_id_shared_foreign FOREIGN KEY (service_id) REFERENCES shared.services(id) ON DELETE SET NULL');
        DB::statement('ALTER TABLE support.credentials ADD CONSTRAINT support_credentials_service_id_shared_foreign FOREIGN KEY (service_id) REFERENCES shared.services(id) ON DELETE RESTRICT');
    }

    public function down(): void
    {
        throw new RuntimeException('Откат shared.services запрещён автоматически: сначала требуется отдельный аудит новых записей и обратного mapping.');
    }

    private function dropForeignKeysToSources(): void
    {
        DB::statement(<<<'SQL'
DO $$
DECLARE item record;
BEGIN
    FOR item IN
        SELECT n.nspname AS schema_name, c.relname AS table_name, con.conname
        FROM pg_constraint con
        JOIN pg_class c ON c.oid = con.conrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        JOIN pg_class target ON target.oid = con.confrelid
        JOIN pg_namespace target_schema ON target_schema.oid = target.relnamespace
        WHERE con.contype = 'f'
          AND (target_schema.nspname || '.' || target.relname) IN
              ('access.services', 'clients.services', 'integration.services', 'dating.services',
               'messenger.services', 'support.services', 'fakes.service', 'pay.service', 'video.service')
    LOOP
        EXECUTE format('ALTER TABLE %I.%I DROP CONSTRAINT %I', item.schema_name, item.table_name, item.conname);
    END LOOP;
END $$;
SQL);
    }

    private function rewriteServiceReferences(): void
    {
        $references = [
            'access.accesses' => 'access.services',
            'clients.accounts' => 'clients.services',
            'integration.data' => 'integration.services',
            'integration.webhooks' => 'integration.services',
            'messenger.service_accounts' => 'messenger.services',
            'support.credentials' => 'support.services',
            'fakes.accounts' => 'fakes.service',
            'fakes.bots' => 'fakes.service',
            'fakes.cards' => 'fakes.service',
            'fakes.proxies' => 'fakes.service',
            'keitaro.webhooks' => 'access.services',
            'questions.surveys' => 'access.services',
            'video.hosting' => 'video.service',
        ];

        foreach ($references as $dependent => $source) {
            [$dependentSchema, $dependentTable] = explode('.', $dependent, 2);
            [$sourceSchema, $sourceTable] = explode('.', $source, 2);
            if (! $this->tableExists($dependentSchema, $dependentTable) || ! $this->tableExists($sourceSchema, $sourceTable)) {
                continue;
            }
            DB::statement(
                "UPDATE {$dependentSchema}.{$dependentTable} d SET service_id = s.id FROM shared.services s WHERE s.source_schema = ? AND s.source_table = ? AND s.source_id = d.service_id",
                [$sourceSchema, $sourceTable],
            );
            $missing = DB::table($dependent)
                ->whereNotNull('service_id')
                ->whereNotIn('service_id', DB::table('shared.services')->select('id'))
                ->count();
            if ($missing > 0) {
                throw new RuntimeException("Не удалось сопоставить {$missing} ссылок service_id в {$dependent}.");
            }
        }
    }

    private function tableExists(string $schema, string $table): bool
    {
        return DB::table('information_schema.tables')->where('table_schema', $schema)->where('table_name', $table)->exists();
    }
};
