<?php

declare(strict_types=1);

return [
    'entities' => [
        'integration_webhooks' => ['entity' => App\Models\IntegrationWebhook::class, 'table' => 'integration.webhooks', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at', 'client_id', 'service_id', 'type_hook_id', 'rules_id', 'cnt', 'dat_last_run']],
        'integration_data' => ['entity' => App\Models\IntegrationData::class, 'table' => 'integration.data', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at', 'webhook_id', 'service_id', 'status_processing']],
        'integration_rules' => ['entity' => App\Models\IntegrationRule::class, 'table' => 'integration.rules', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at', 'type_processing_id']],
        'integration_services' => ['entity' => App\Models\IntegrationService::class, 'table' => 'integration.services', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'integration_type_hook' => ['entity' => App\Models\IntegrationHookType::class, 'table' => 'integration.type_hook', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'integration_type_processing' => ['entity' => App\Models\IntegrationProcessingType::class, 'table' => 'integration.type_processing', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'client_doc_types' => ['entity' => App\Models\DocType::class, 'table' => 'clients.doc_types', 'global' => true, 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'status', 'settings', 'created_at', 'updated_at', 'deleted_at']],
        'client_documents' => ['entity' => App\Models\Document::class, 'table' => 'clients.documents', 'global' => false, 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'client_id', 'doc_type_id', 'executor_id', 'customer_id', 'amount', 'status', 'comment', 'internal_comment', 'src', 'doc_date', 'accepted_at', 'payed_at', 'canceled_at', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'client_individuals' => ['entity' => App\Models\ClientIndividual::class, 'table' => 'clients.individuals', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'firstname', 'middlename', 'lastname', 'phone', 'email', 'birthday', 'passport_seria', 'passport_number', 'passport_date', 'passport_kem', 'passport_code', 'address_reg', 'vodud_date', 'vodud_nomer', 'user_id', 'manager_id', 'client_id', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'goods' => ['entity' => App\Models\Good::class, 'table' => 'goods.goods', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'code', 'parent_id', 'parent_code', 'type_good', 'type_unit', 'barcodes', 'articul', 'src', 'is_from_external', 'is_category', 'has_children', 'level', 'goodcard_id', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'goods_marketplace' => ['entity' => App\Models\GoodMarketplace::class, 'table' => 'wms.goods_marketplace', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'integration_id', 'webhook_id', 'marketplace', 'external_id', 'external_sku', 'offer_id', 'name', 'barcodes', 'status', 'good_id', 'match_type', 'matched_at', 'synced_at', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'orders' => ['entity' => App\Models\Order::class, 'table' => 'wms.orders', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'code', 'number', 'client_id', 'warehouse_id', 'delivery_service_id', 'order_status_id', 'order_source_id', 'order_cancel_status_id', 'integration_id', 'delivery_track', 'delivery_date', 'created_date', 'currency', 'goods_total_price', 'goods_count', 'comment_partner', 'comment_internal', 'custom', 'need_imei', 'need_uin', 'need_gtin', 'need_sgtin', 'need_expiration', 'need_gtd', 'is_b2b', 'is_crossborder', 'wb_supply_id', 'crm_party_id', 'crm_party_address_id', 'status', 'tenant_id', 'src', 'created_at', 'updated_at', 'deleted_at']],
        'order_statuses' => ['entity' => App\Models\OrderStatus::class, 'table' => 'wms.order_statuses', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'code', 'status', 'tenant_id', 'src', 'created_at', 'updated_at', 'deleted_at']],
        'order_sources' => ['entity' => App\Models\OrderSource::class, 'table' => 'wms.order_sources', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'code', 'status', 'tenant_id', 'src', 'created_at', 'updated_at', 'deleted_at']],
        'order_cancel_statuses' => ['entity' => App\Models\OrderCancelStatus::class, 'table' => 'wms.order_cancel_statuses', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'code', 'status', 'tenant_id', 'src', 'created_at', 'updated_at', 'deleted_at']],
        'logistic_companies' => ['entity' => App\Models\LogisticCompany::class, 'table' => 'wms.logistic_companies', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'code', 'status', 'tenant_id', 'src', 'created_at', 'updated_at', 'deleted_at']],
        'shipment_statuses' => ['entity' => App\Models\ShipmentStatus::class, 'table' => 'wms.shipment_statuses', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'code', 'status', 'tenant_id', 'src', 'created_at', 'updated_at', 'deleted_at']],
        'shipments' => ['entity' => App\Models\Shipment::class, 'table' => 'wms.shipments', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'code', 'order_id', 'client_id', 'warehouse_id', 'shipment_status_id', 'created_date', 'checked_at', 'sent_at', 'status', 'tenant_id', 'src', 'created_at', 'updated_at', 'deleted_at']],
        'good_cards' => ['entity' => App\Models\GoodCard::class, 'table' => 'goods.good_cards', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'good_id', 'name', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'type_goods' => ['entity' => App\Models\GoodType::class, 'table' => 'goods.type_goods', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'unit_goods' => ['entity' => App\Models\GoodUnit::class, 'table' => 'goods.unit_goods', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'kind_kiz' => ['entity' => App\Models\KindKiz::class, 'table' => 'goods.kind_kiz', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'marketplaces' => ['entity' => App\Models\Marketplace::class, 'table' => 'wms.marketplaces', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'status', 'icon', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'delivery_services' => ['entity' => App\Models\DeliveryService::class, 'table' => 'wms.delivery_services', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'status', 'icon', 'color', 'is_order_edit', 'from_integration_only', 'prefix', 'folder', 'marketplace_id', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'warehouses' => ['entity' => App\Models\Warehouse::class, 'table' => 'wms.warehouses', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'code', 'type_warehouse_id', 'kind_warehouse_id', 'address', 'timezone', 'contact_name', 'contact_phone', 'working_hours', 'width', 'height', 'scheme_json', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'type_warehouses' => ['entity' => App\Models\TypeWarehouse::class, 'table' => 'wms.type_warehouses', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'kind_warehouses' => ['entity' => App\Models\KindWarehouse::class, 'table' => 'wms.kind_warehouses', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'type_storage' => ['entity' => App\Models\TypeStorage::class, 'table' => 'wms.type_storage', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'zones' => ['entity' => App\Models\Zone::class, 'table' => 'wms.zones', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'cells' => ['entity' => App\Models\Cell::class, 'table' => 'wms.cells', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'warehouse_id', 'zone_id', 'name', 'shortname', 'row', 'level', 'number', 'priority', 'type_storage_id', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'cell_goods' => ['entity' => App\Models\CellGood::class, 'table' => 'wms.cell_goods', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'warehouse_id', 'cell_id', 'good_id', 'user_id', 'cnt', 'put_at', 'leave_at', 'tenant_id', 'src', 'created_at', 'updated_at', 'deleted_at']],
        'acceptances' => ['entity' => App\Models\Acceptance::class, 'table' => 'wms.acceptances', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'code', 'client_id', 'warehouse_id', 'task_id', 'plan_count', 'fact_count', 'progress', 'type_acceptance_id', 'created_at', 'started_at', 'finished_at', 'updated_at', 'deleted_at', 'status', 'tenant_id', 'src']],
        'type_acceptance' => ['entity' => App\Models\TypeAcceptance::class, 'table' => 'wms.type_acceptance', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'type_services' => ['entity' => App\Models\TypeService::class, 'table' => 'wms.type_services', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'services_ff' => ['entity' => App\Models\ServiceFf::class, 'table' => 'wms.services_ff', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'status', 'unit_id', 'price', 'type_service_ff', 'tenant_id', 'is_visible', 'created_at', 'updated_at', 'deleted_at']],
        'tasks' => ['entity' => App\Models\Task::class, 'table' => 'wms.tasks', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'code', 'name', 'shortname', 'client_id', 'task_type_id', 'task_stage_id', 'status_id', 'planned_at', 'started_at', 'completed_at', 'charged_at', 'charged_sum', 'confirmed_at', 'comment', 'internal_comment', 'priority_id', 'src', 'order_id', 'warehouse_id', 'user_id', 'created_by_user_id', 'fact_count', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'scheduler_tasks' => ['entity' => App\Models\SchedulerTask::class, 'table' => 'public.scheduler_tasks', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'module', 'task_type', 'target', 'options', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'scheduler' => ['entity' => App\Models\Scheduler::class, 'table' => 'public.scheduler', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'module', 'tenant_id', 'task_key', 'task_type', 'params', 'schedule', 'status', 'next_run_at', 'last_run_at', 'created_at', 'updated_at', 'deleted_at']],
        'task_stages' => ['entity' => App\Models\TaskStage::class, 'table' => 'wms.task_stages', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'status', 'icon', 'tenant_id', 'src', 'created_at', 'updated_at', 'deleted_at']],
        'imported_users' => ['entity' => App\Models\ImportedUser::class, 'table' => 'wms.users', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'code', 'name', 'shortname', 'first_name', 'last_name', 'patronymic', 'email', 'phone', 'login', 'status', 'tenant_id', 'src', 'created_at', 'updated_at', 'deleted_at']],
        'task_goods' => ['entity' => App\Models\TaskGood::class, 'table' => 'wms.task_goods', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'task_id', 'good_id', 'shipment_box_number', 'count_plan', 'count_fact', 'good_comment', 'good_current_barcode', 'unit_price', 'unit_price_currency_id', 'src', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'task_types' => ['entity' => App\Models\TaskType::class, 'table' => 'wms.task_types', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'status', 'icon', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'task_statuses' => ['entity' => App\Models\TaskStatus::class, 'table' => 'wms.task_statuses', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'status', 'icon', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'priorities' => ['entity' => App\Models\Priority::class, 'table' => 'wms.priorities', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'status', 'icon', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'kizes' => ['entity' => App\Models\Kiz::class, 'table' => 'goods.kizes', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'code', 'client_id', 'kind_kiz_id', 'good_id', 'entranced_at', 'leaving_at', 'printed_at', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'client_companies' => ['entity' => App\Models\ClientCompany::class, 'table' => 'clients.companies', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'fullname', 'inn', 'kpp', 'ogrn', 'okpo', 'phone', 'email', 'site', 'director_fio', 'director_position', 'bank', 'bik', 'korr_schet', 'rasch_schet', 'client_id', 'src', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at'], 'json_fields' => ['src' => ['telegram', 'opf', 'accountant_position', 'accountant_fio', 'legal_address', 'is_own', 'is_client', 'is_partner']]],
        'client_services' => ['entity' => App\Models\ClientService::class, 'table' => 'clients.services', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'client_accounts' => ['entity' => App\Models\ClientAccount::class, 'table' => 'clients.accounts', 'authorize' => [App\Services\AccessService::class, 'isAdmin'], 'fields' => ['id', 'name', 'shortname', 'host', 'login', 'pass', 'token', 'descr', 'status', 'group_id', 'server_id', 'src', 'client_id', 'service_id', 'tenant_id', 'created_at', 'updated_at', 'deleted_at']],
        'modules' => [
            'entity' => App\Models\Module::class,
            'table' => 'main.modules',
            'global' => true,
            'authorize' => [App\Services\AccessService::class, 'isAdmin'],
            'fields' => ['id', 'name', 'shortname', 'descr', 'fn', 'domain', 'status', 'created_at', 'updated_at', 'deleted_at'],
        ],
        'features' => [
            'entity' => App\Models\Feature::class,
            'table' => 'main.features',
            'global' => true,
            'authorize' => [App\Services\AccessService::class, 'isAdmin'],
            'fields' => ['id', 'name', 'shortname', 'is_resource', 'module_id', 'status', 'created_at', 'updated_at', 'deleted_at'],
        ],
        'icons' => [
            'entity' => App\Models\Icon::class,
            'table' => 'main.icons',
            'global' => false,
            'authorize' => [App\Services\AccessService::class, 'isAdmin'],
            'fields' => ['id', 'name', 'path', 'category', 'size', 'ext', 'user_id', 'company_id', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at'],
        ],
        'files' => [
            'entity' => App\Models\File::class,
            'table' => 'main.files',
            'global' => false,
            'authorize' => [App\Services\AccessService::class, 'isAdmin'],
            'fields' => ['id', 'name', 'path', 'category', 'size', 'ext', 'user_id', 'company_id', 'is_s3', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at'],
        ],

        'clients' => [
            'entity' => App\Models\Client::class,
            'table' => 'clients.clients',
            'authorize' => [App\Services\AccessService::class, 'isAdmin'],
            'fields' => ['id', 'name', 'shortname', 'code', 'status', 'src', 'tenant_id', 'created_at', 'updated_at', 'deleted_at'],
        ],
        'companies' => [
            'entity' => App\Models\Company::class,
            'table' => 'main.companies',
            'authorize' => [App\Services\AccessService::class, 'isAdmin'],
            'fields' => ['id', 'name', 'shortname', 'fullname', 'inn', 'kpp', 'ogrn', 'phone', 'email', 'site', 'director_fio', 'director_position', 'bank', 'bik', 'korr_schet', 'rasch_schet', 'src', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at'],
            'json_fields' => ['src' => ['telegram', 'opf', 'accountant_position', 'accountant_fio', 'legal_address', 'is_own', 'is_client', 'is_partner']],
        ],
        'company_contacts' => [
            'entity' => App\Models\CompanyContact::class,
            'table' => 'main.company_contacts',
            'authorize' => [App\Services\AccessService::class, 'isAdmin'],
            'fields' => ['id', 'name', 'shortname', 'company_id', 'val', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at'],
        ],
        'users' => [
            'entity' => App\Models\User::class,
            'table' => 'public.users',
            'authorize' => [App\Services\AccessService::class, 'isAdmin'],
            'fields' => ['id', 'name', 'last_name', 'middle_name', 'nick', 'email', 'phone', 'status', 'roles', 'tenant_id', 'created_at', 'updated_at', 'deleted_at'],
            'projector' => App\Services\Sync\UserSyncPayloadProjector::class,
        ],
        'roles' => [
            'entity' => App\Models\Role::class,
            'table' => 'main.roles',
            'authorize' => [App\Services\AccessService::class, 'isAdmin'],
            'fields' => ['id', 'name', 'slug', 'description', 'system', 'tags', 'status', 'company_id', 'tenant_id', 'created_at', 'updated_at', 'deleted_at'],
        ],
        'permissions' => [
            'entity' => App\Models\Permission::class,
            'table' => 'main.permissions',
            'authorize' => [App\Services\AccessService::class, 'isAdmin'],
            'fields' => ['id', 'name', 'slug', 'resource', 'system', 'status', 'module_id', 'feature_id', 'tenant_id', 'created_at', 'updated_at', 'deleted_at'],
        ],
        'permission_roles' => [
            'entity' => App\Models\PermissionRole::class,
            'table' => 'main.permission_role',
            'authorize' => [App\Services\AccessService::class, 'isAdmin'],
            'fields' => ['id', 'role_id', 'permission_id', 'status', 'tenant_id', 'created_at', 'updated_at', 'deleted_at'],
        ],
    ],
];
